### ISSUE TITLE
Invoice status `processing` is missing

### ISSUE THREAD

**Issue by kamermans** [maxio-com/ab-golang-sdk#36]
I see that the Golang SDK and the API docs do not have the Invoice Status `processing`, but the normal documentation does say this status can exist: https://maxio-chargify.zendesk.com/hc/en-us/articles/5405078794253-Introduction-to-Invoices#invoice-statuses

Golang:
https://github.com/maxio-com/ab-golang-sdk/blob/4d92f5e7ae3db6f7faf08203f05cdf07af8aad16/models/enums.go#L2713-L2718

API Docs:
https://developers.maxio.com/http/advanced-billing-api/models/enumerations/invoice-status

Is it true that an invoice can be in the status `processing`?

**Comment by maciej-nedza** [comment]
Hi @kamermans, thanks for reporting this issue. You’re correct—there is a processing invoice status currently missing from both the API documentation and the SDK, though it is available within the API. This status can appear for subscriptions using the direct debit payment method (GoCardless) while waiting for payment acknowledgment.

We’ll add this status to the API specification and SDK and will notify you once it’s done. Since it may take some time to coordinate the SDK release, could you let us know if this issue is blocking you, are you using the Go SDK and the Direct Debit payment method?

**Comment by kamermans** [comment]
OK, thanks @maciej-nedza!
I don't use that payment method, so it's not blocking me at all.

**Comment by maciej-nedza** [comment]
Fixed in `v0.5.0`.
